version: '3'

services:
  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_DB : process_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data