spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/process_management
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    baseline-on-migrate: true
